services:
  postgres:
    image: postgres:16-alpine
    container_name: cron-jobs-nestjs_bd
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    env_file:
      - local.env
    environment:
      POSTGRES_USER: '${DATABASE_USER:-postgres}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD:-postgres}'
      POSTGRES_DB: '${DATABASE_NAME:-postgres}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_NAME:-postgres}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
